# Generated by Django 5.0 on 2023-12-11 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projet',
            name="Please 'Besion' must be greater then 0",
        ),
        migrations.AddConstraint(
            model_name='projet',
            constraint=models.CheckConstraint(check=models.Q(('besoin__gt', 0)), name="Please 'Besion' must be greater then 0"),
        ),
    ]
